# Generated by Django 2.0.2 on 2018-03-06 23:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this event', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('art', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this user', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('favorite_albums', models.CharField(max_length=200)),
                ('favorite_genres', models.CharField(max_length=200)),
                ('hobbies', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('anthem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_anthem', to='Tunes.Song')),
                ('current_song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_current_song', to='Tunes.Song')),
                ('events_attended', models.ManyToManyField(related_name='user_events_attended', to='Tunes.Event')),
                ('events_attending', models.ManyToManyField(related_name='user_events_attending', to='Tunes.Event')),
                ('events_hosting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_events_hosting', to='Tunes.Event')),
                ('favorite_songs', models.ManyToManyField(to='Tunes.Song')),
                ('followers', models.ManyToManyField(related_name='user_followers', to='Tunes.User')),
                ('following', models.ManyToManyField(related_name='user_following', to='Tunes.User')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_host', to='Tunes.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='people',
            field=models.ManyToManyField(related_name='people_attending', to='Tunes.User'),
        ),
    ]
