# Generated by Django 2.0.2 on 2018-03-08 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tunes', '0003_auto_20180308_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_albums',
        ),
        migrations.AlterField(
            model_name='user',
            name='current_song',
            field=models.ForeignKey(blank=True, help_text='Currently listened to song', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_current_song', to='Tunes.Song'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_genres',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_genres',
            field=models.ManyToManyField(to='Tunes.Genre'),
        ),
    ]
