# Generated by Django 2.0.2 on 2018-04-16 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tunes', '0004_event_other_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='(yyyy-mm-dd hh:mm:ss)', verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='(yyyy-mm-dd hh:mm:ss)', verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='web_link',
            field=models.URLField(blank=True, help_text='(http(s)://...)', max_length=250, null=True, verbose_name='Web Link'),
        ),
    ]
