# Generated by Django 2.0.2 on 2018-03-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tunes', '0005_auto_20180308_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='city',
            new_name='name',
        ),
    ]
