# Generated by Django 2.0.2 on 2018-03-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tunes', '0010_auto_20180320_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
