# Generated by Django 2.0.2 on 2018-03-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tunes', '0011_auto_20180320_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='web_link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
