# Generated by Django 2.0.2 on 2018-03-21 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tunes', '0012_auto_20180320_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='playlists',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist_user', to='Tunes.Playlist'),
        ),
        migrations.AddField(
            model_name='user',
            name='rotation',
            field=models.ManyToManyField(blank=True, null=True, to='Tunes.Album'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(blank=True, help_text='Playlist Name', max_length=250, null=True),
        ),
    ]
