# Generated by Django 2.0.2 on 2018-03-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tunes', '0013_auto_20180320_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='playlists',
        ),
        migrations.AddField(
            model_name='user',
            name='playlists',
            field=models.ManyToManyField(blank=True, null=True, related_name='playlist_user', to='Tunes.Playlist'),
        ),
    ]
