# Generated by Django 2.0.2 on 2018-03-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tunes', '0014_auto_20180320_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/events/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/users/'),
        ),
    ]
