# Generated by Django 2.0.2 on 2018-03-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tunes', '0015_auto_20180322_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='other_events',
            field=models.ManyToManyField(related_name='other_events_occuring', to='Tunes.Event'),
        ),
    ]
