# Generated by Django 2.0.2 on 2018-03-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tunes', '0016_event_other_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='art',
            field=models.ImageField(upload_to='images/albums/'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='embed_code',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rotation',
            field=models.ManyToManyField(to='Tunes.Album'),
        ),
    ]
